### ISSUE TITLE
Can't Run Convergence

### ISSUE THREAD

**Issue by me12722** [worldofbalance/client#16]
Hey I cant seem to run convergence, i have the server up and running and i changed the config file on the client side and they are communicating but I get a blue screen whenever I enter the convergence game. Anybody else having this issue?

**Comment by jensvdh** [comment]
@worldofbalance/convergence

**Comment by dlhoff** [comment]
Perhaps you want to at least try the steps in the post i made on iLearn on how to get both the client and server running Convergence locally. This was done using the lobby-server which is not the preferred repository now. However, if it works for you it would help isolate the problem.  The iLearn link is:

https://ilearn.sfsu.edu/ay1516/mod/forum/discuss.php?d=140604

David

**Comment by jensvdh** [comment]
Can someone add these iLearn steps to the wiki so everyone can see them? Thanks!

**Comment by me12722** [comment]
@david I already did those things. I get a blue screen @fito has the same issue with all minigames.

**Comment by dlhoff** [comment]
Copied from iLearn post as Jens requested. Everyone can also see all items on iLearn:

I wanted to get both the client and server running locally to have an environment for development.
I did a git clone of the unity-game-client and lobby-server. [I understand that the Convergence
server is inside the lobby-server.] I ran the unity-game-client and it connects to remote server
and works. I could login. First, i wanted to change the unity-game-client to communicate over
localhost. In Assets/Scripts/Config.cs, i changed REMOTE_HOST to "localhost".

This seemed to be the only change necessary.

After that I ran the unity-game-client and it tried to communicate on localhost.

Since i did not have the lobby-server running, it was not able to make a connection.

This way i verified that it was trying on localhost.

I ran the lobby_server in Netbeans and it could not open the wob.sql file. I tried a bunch of things
and could not get the local copy of wob.sql to work. I decided at this point it was ok in the
development process to use the remote database on smurf. So, i changed file conf/db.conf to use
these credentials:

DBURL smurf.sfsu.edu
DBName wob
DBUsername wob
DBPassword asd123

This solved the database problem. I was accessing the smurf database.

I had problems with the class MiniGameServers. In the initMiniGames() method it tries to queue up
Running Rhino and Cards of the Wild using jar files to start those mini games. The problem is that i could not find these jar
files in the paths indicated. So, when the server starts up, it gives error messages. I commented
out the block of code below:

```
    game = new MiniGame("Running Rhino");
    game.setAsMultiPlayerGame("../Speed_Server/dist/Speed_Server.jar", 20039);
    miniGames.put(game.getName(), game);

    game = new MiniGame("Cards of the Wild");
    game.setAsMultiPlayerGame("../WoC_Server/dist/Cards_Server.jar", 20038);
    miniGames.put(game.getName(), game);
```

After that, the server started up without any error messages.

I ran the unity-game-client and they made a connection. I was able to Register a new user/password
and login. Also, i was able to run the Convergence game. It worked well. With the remote server, only
about 20% of the time for me would a change in graph appear after pressing the Submit button. However,
with the local server, it works about every time. Also, the Netbeans console shows that ecosystem
information is being retrieved.

I think the atn simulator is still running remotely which is ok for now.

There are a few things to work on:
1. Errors messages occur for database problems. Like:
Column 'atn_manipulation_id' not found.
SQL exception: Unknown column 'csv_atn' in 'field list', cause: null
2. The Unity console said several times that connection failed and reconnecting. Yet, the login
still worked. I did not see this problem on the project 1 server work.

**Comment by dlhoff** [comment]
@me12722 I also see the blue screen for up to 30 seconds before it transitions to the Lobby. Does your blue screen last for more than 60 seconds?  Also, are you running mac or Windows? I think @Fito runs mac. I am running Windows 7. I will investigate and see if i can offer a suggestion on how to fix.

**Comment by me12722** [comment]
The blue screen doesn't go away i left it there for 10 minutes, I am also running a mac.

**Comment by dlhoff** [comment]
Did you check the NetBeans console log? It may show an error message. 

Also, you can pause the Client and check its log. The Client log shows all of the request messages sent to the Server and the response received from the Server. For each request, there normally is a response. There may be a request sent and no response received. Then, on the NetBeans console there may be a message that helps understand the problem. 

Do you start the Server first and wait until you see the message "> Now accepting connections..." before starting the Client? I always wait for this message before starting the Clients. 

Perhaps the problem is Server credentials. Here are all my Server credential file names and their values:

db local.conf:
#Database URL
DBURL localhost

#Database name
DBName WOB

#Database user name
DBUsername root

#Database user password
DBPassword root

db.conf:
#Database URL
DBURL localhost

#Database name
#DBName csc63101
DBName wob

#Database user name
DBUsername root

#Database user password
DBPassword newpwd

db.conf local:
#Database URL
DBURL localhost

#Database name
DBName WOB_DB

#Database user name
DBUsername root

#Database user password
DBPassword root

You can use the debugger to step through the Server operation on NetBeans or the other thing i do in these situations is add a lot of console print messages in the form of:

NetBeans:
Log.println("message, value x = " + x);

Unity/C#:
Debug.Log ("message, value x = " + x);

I scatter these about to isolate where the problem is and then drill down on it.

**Comment by haichuand** [comment]
Per Dr. Yoon's instructions, I'm using the database on thecity.sfsu.edu. I
imported the 'simtest_node_params' table from smurf to thecity; added
'atn_manipulation_id' column in ecosystem table; added 'csv_atn' column in
sim_job table to fix some of the SQL exceptions when running server.

**Comment by ilmiyoon** [comment]
Any progress on this?
How many have succeeded in running Convergence game on Mac or on Windows? Can you inform here?

**Comment by me12722** [comment]
Yeah,  Jason and I had corrupted .txt files and then Gilbert and I found
that you have to change the path for the simulation files on the server
side.

**Comment by Fito** [comment]
I'm able to start the game, but then I see only a gray screen, and the following errors show up in the console:
- `NullReferenceException: Object reference not set to an instance of an object
  ConvergeGame.MakeWindow (Int32 id) (at Assets/Scripts/ConvergeGame/ConvergeGame.cs:164)
  UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)`
- `GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced)`

**Comment by me12722** [comment]
You probably have a corrupted  covergence.txt file

**Comment by dlhoff** [comment]
Jason came by for help this morning with the same error message. We looked at the code and concluded the same thing me12722 told you. There seems to be a problem with his 
converge-ecosystems.txt file. So, i emailed him mine and he replaced it and it worked.
I attached the file. This file has some binary characters at the beginning. So, you cannot 
open it with a text editor and save it back. 

[converge-ecosystems.txt](https://github.com/worldofbalance/unity-game-client/files/203612/converge-ecosystems.txt)

**Comment by haichuand** [comment]
Somehow I didn't have this problem. I checkout out the cvg-refactor branch for unity-game-client, and the lby-refactor banch for lobbyServer. I am using localhost server connected to thecity.sfsu.edu database. I can run all the simulations multiple times without errors.

**Comment by me12722** [comment]
You're supposed to be on wob-server

**Comment by haichuand** [comment]
Really? I thought the convergence game should run on lobby-server. Please check David's earlier post.

**Comment by me12722** [comment]
Yeah but we found that the other repo is missing some files, there are some
problems with that server but they're easy to fix. We should meet during
class time and get everyone on the same page. You should be fine as long as
everything runs with your current setup
