### ISSUE TITLE
Making settings in Config.cs configurable (local or remote)

### ISSUE THREAD

**Issue by rupalkhilari** [worldofbalance/client#33]
While discussing a change in Assets/Scripts/Config.cs in [this thread](https://github.com/worldofbalance/unity-game-client/commit/8b734a4e486bbd32de742a28355e40567737ed53), @jensvdh suggested that we could use an environment variable to toggle local settings in Config.cs. That way we would not have to deal with switching the REMOTE_HOST variable each time between testing the server locally and in production. I think it would be nice to have this setting configurable. 

On a separate note, we also need to update the Config.cs to use the production server thecity.sfsu.edu once it is running. It currently seems to be using the IP address 52.32.228.220.

**Comment by niculistana** [comment]
@rupalkhilari Good idea. I also want to reference the following iLearn posts that Prof. @ilmiyoon  posted regarding running jar files in thecity.sfsu.edu:

https://ilearn.sfsu.edu/ay1516/mod/forum/discuss.php?d=152025
https://ilearn.sfsu.edu/ay1516/mod/forum/discuss.php?d=148919

Also, the location for the minigame server jar in our repositories can be located under: /path-to-your-server/mini_game_server_jar

**Comment by niculistana** [comment]
@worldofbalance/server please follow this thread and let us know what you think!

**Comment by brianxautumn** [comment]
On Don't eat me, since it isn't 2 player do we have to do anything extra, or just leave i with whatever connection was already going?

**Comment by niculistana** [comment]
@brianxautumn @jensvdh mentioned that we have to migrate server code to different folders, and build its own jar file to run separately from the lobby server. If Don't Eat Me does not have a server then you should be ok.

**Comment by niculistana** [comment]
Hi everyone, here is a quick guide on our port usage:

If you are using `remote host = 52.32.228.220`, you must use the following port `9255` for the lobby server.

If you are using `remote host = localhost`, you must use the following port `20041` for the lobby server. It is important that you **both** change port on `Constants.cs` script in the client as well as the port on `gameServer.conf` file in the server, otherwise you will get a `connection refused` error.

**Comment by niculistana** [comment]
I am currently working on deploying jar files. We need to define reserved ports for our Ubuntu instance so it does not clash with anything else that is running on `thecity.sfsu.edu`. 

Also, few people have pointed out that we need our own `worldofbalance` user account within `thecity.sfsu.edu` to ease management, and have multiple users have access instead of having 1 student managing the account to restart and update servers. @ilmiyoon What do you think?

**Comment by niculistana** [comment]
Currently there is a java server running on my `listana` account in `thecity.sfsu.edu`. It uses the following ports:

lobby: 9255
cow: 20038
rno: 20039
sdv: 20040

I only tested the lobby's requests/response. I suggest @worldofbalance/server test their own requests/response for their own specific servers. Please create issues as you encounter them and I'll try to help. Also, feel free to ping me if you need to restart the server.

**Comment by Fito** [comment]
@rupalkhilari @jensvdh I open a pull request related to this issue: https://github.com/worldofbalance/unity-game-client/pull/67

**Comment by Fito** [comment]
https://github.com/worldofbalance/unity-game-client/pull/67 has been merged, which addresses this issue. However, there is a lot of information in this issue that I'm not sure if we should close it

**Comment by niculistana** [comment]
@Fito, I created a wiki regarding this post: https://github.com/worldofbalance/unity-game-client/wiki/[Config]-Environment-variables

**Comment by Fito** [comment]
Thanks @niculistana I'm closing this issue.
