### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by brianxautumn** [worldofbalance/client#52]
Theres a null exception error when logging into the lobby. Does anyone else see this?
<img width="601" alt="screen shot 2016-04-14 at 1 39 36 pm" src="https://cloud.githubusercontent.com/assets/6754528/14542915/6372eb36-0246-11e6-9bb8-a48b1922ca83.png">
<img width="1037" alt="screen shot 2016-04-14 at 1 39 27 pm" src="https://cloud.githubusercontent.com/assets/6754528/14542916/638716ec-0246-11e6-88e7-ed94860a11ea.png">

**Comment by rupalkhilari** [comment]
This is related to the fact that the script making a connection to the Sea Divided server was removed from the global object due to the server not being deployed in production yet. @Fito had reported that it was hanging the application due to that and would need to be removed temporarily.
It shouldn't affect the functioning of the project as a whole other than the SD game. I will look into merging the branch containing the fix for this into development.

**Comment by rupalkhilari** [comment]
I have created a pull request https://github.com/worldofbalance/unity-game-client/pull/54 that fixes this until we have migrated to the integrated network manager.
