### ISSUE TITLE
Two Network Managers in Assets/Game scene

### ISSUE THREAD

**Issue by dlhoff** [worldofbalance/client#7]
I was checking the Unity log while running the Game client and noticed repeated Connection Failed messages. They were coming from the CW Network Manager that is a part of that scene. There are two Network Managers in that scene. The main on and the CW one. Both use their own Connection 
Manager to setup a tcp connection. This seems to be causing the error. So, i deleted the CW Network Manager and the error message went away. I am posting this here to see if anyone knows why there are two Network Managers in the Game scene.

**Comment by jensvdh** [comment]
@dlhoff I think having 2 network managers is an artifact of last semester's code not being integrated properly. If they are both the exact same class then I'm assuming we can get rid of one of them.

Are you seeing any side-effects as a result of removing that one network manager?

**Comment by dlhoff** [comment]
I am not seeing any side effects. Probably because i am working with the Multiplayer Convergence game, not the CW game. After studying the code more, i think i understand the reason the setup two Network Managers. CW has a separate server. When you leave the lobby and go to CW, then the client starts communicating with the CW server instead of the lobby server. I think they initiated both connections so that the CW server would be connected when you switch to that game. We will have to address this issue in Multiplayer Convergence because we have been instructed to take the Convergence server out of the lobby server. [Right now i am testing the multiplayer client with the Convergence server still in the lobby server.]  I am wondering if it would be possible to establish the connection to game-specific server right before the client switches to the game. I was thinking the sequence could be:
1. User selects specific game (like CW, Multiplayer Convergence).
2. Connection to lobby server is closed.
3. Establish connection to game-specific server (on a different port). 
4. Client loads game-specific scene and continues from there.
What do you think? 
The issue of sending information back to the lobby (like change in money) must be addressed. 
Perhaps the game-specific server could send it back to the lobby server.

**Comment by jensvdh** [comment]
Can we have two instances of the same class?

@rujoota and @rupalkhilari are part of the CoW team so maybe they can give you more insight on how this may affect their server code. Thoughts?

**Comment by jensvdh** [comment]
@worldofbalance/cards-of-wild

**Comment by rujoota** [comment]
Yes, last semester they were using separate COW and RR server and hence in unity they are sending multiple login requests/player select or other requests. We would be working towards managing that part, but I think it should not affect other games. Meanwhile, temporarily you can comment that part of code and check if it works fine.

**Comment by jensvdh** [comment]
@dlhoff Can you comment out that specific network manager and make a PR? Then we'll merge that into development. Thanks!

**Comment by dlhoff** [comment]
I would prefer not to merge at this time. I've done so many changes to the unity-game client as i am now in the middle of implementing the multiplayer mode. I don't want to merge what i have now into development. I am in the middle of implementation. The change is easy. Open assets/Game.unity - the starting game scene. This scene should be opened by default when you load the unity-client project. Then, click on Global Object. You will see two Network Manager scripts instantiated. Remove the script of the bottom one. It is the CW Network Manager. 

BTW - referring to your previous comment about having two instances of the same class. They are not the same class. They both show up as Network Manager. However, one is from the lobby-server general library. The other is from the CW namespace. It is the CW specific Network Manager. I think it is mostly a copy of the general Network Manager - but it is a different class.

**Comment by Fito** [comment]
I've been looking at the Network Managers. They are different implementations of the same idea (a network manager). The code looks different but that's only because they were not using source control last semester, and every team developed their own Network Manager. When the time came to integrate the games, the easy route was to just namespace them. I'm trying to refactor them into one configurable Network manager that all minigames can use, but I'm finding it a little overwhelming due to the amount of hardcoded values and poorly named variables. I'll keep trying to unravel them.

**Comment by Fito** [comment]
I looked at the two networks managers. The one under global space and the one under the CW namespace are identical. I was able to delete most of the files under CW's network scripts directory and the game compiled without errors. I had to remove some namespaced calls, but other than that it seemed OK. 
However, I have not thoroughly tested it, so I'll leave that to the CW team to remove.

**Comment by jensvdh** [comment]
@Fito can you make a branch or PR with those changes so the @worldofbalance/cards-of-wild team can test it?

**Comment by Fito** [comment]
@jensvdh since I jsut experimenting, I undid my changes. I'll do it again and make a PR

**Comment by jensvdh** [comment]
@Fito Thanks for the hard work. Let me know when you think we can merge the deduplication of the Network Managers.

**Comment by ilmiyoon** [comment]
@Fito Thanks for the hard work. Why don't you make a branch with changes, so CoW can test...? Or was it already done?

**Comment by Fito** [comment]
@ilmiyoon I got distracted working on other things. However, I found more errors that I can't figure out yet. I'll get a branch up by tomorrow morning, so the CoW team can help me figure it out.

**Comment by Fito** [comment]
I solved the errors I was seeing. I removed the duplicate classes and everything seems to work fine.
I made a pull request (https://github.com/worldofbalance/unity-game-client/pull/15) with my changes so the @worldofbalance/cards-of-wild team can test it.

**Comment by jensvdh** [comment]
Since #15 has been merged. Can we close this issue?

**Comment by dlhoff** [comment]
Per Jens suggestion and the fixed explained, i closed this.

**Comment by anuagg** [comment]
@jensvdh @Fito @dlhoff @rujoota -The reason behind those repeated Connection Failed messages  was that client was trying to connect to cw server and since we didn't had our minigame servers running back then, there was nothing to connect to. 
As @dlhoff had mentioned earlier, those two networkManager classes are not the same. They had same function and hence same code. But they both have separate instances of Connection manager, each instance holding a socket connection to the port. As we need two sockets to communicate to lobby server and cw server. 
Thus, merging the two, makes the code for lobby server run perfectly, but since NetworkManager code is coded in a way to hold only one instance of connectionManager, cw won't call its connection Manager.
Removing one of the classes won't solve the problem. Either we have to add code in a single class to handle both the connections or backtrack to the point where we had two classes.

Since I sense some problem here m reopening this issue.

**Comment by ilmiyoon** [comment]
Great point!
@Fito made the configuration file for mini games on the client side. And it should list the port numbers and we should make the NetworkManager class creates separate instances with each port numbers. @Fito, can you work on this?

**Comment by Fito** [comment]
@ilmiyoon @anuagg 
I see, I focused mainly on eliminating repeated code (The network managers were identical). I'll make it so we create separate instances.

**Comment by Fito** [comment]
@anuagg @ilmiyoon 
I modified the NetworkManager class so that it gets instantiated for different games.
I also removed the duplicate ConnectionManager, and made the port and host injectable into the constructor.
ConnectionManagers are now injected into NetworkManagers, instead of it being instantiated within the class.

I'm still not able to test this myself because I can't/don't know how to properly run CoW. I believe I need two clients to run the game properly, but I can't open a separate instance of Unity on my Mac.
Could someone from @worldofbalance/cards-of-wild test it? 

Here's the pull request:
https://github.com/worldofbalance/unity-game-client/pull/24

**Comment by dlhoff** [comment]
As an FYI, I run two copies of Unity on my Windows 7 laptop by copying the entire Unity folder to another name and loading the second copy from that directory. For example, i have a unity-game-client folder. Then, i copy it to unity-game-client-dummy. I run two copies of Unity, each one loading the same program, but from two different folders. This is how i test out Multiplayer Convergence.

**Comment by ilmiyoon** [comment]
GREAT!!
Also now you should be able to run the server at theCity! TheCity has JDK 1.8 as I announced at iLearn news. (But this still needs CoW team test if it works properly)

**Comment by Fito** [comment]
@dlhoff thanks! I'll try that.

**Comment by ilmiyoon** [comment]
@worldofbalance/cards-of-wild Did any one test this?

**Comment by Fito** [comment]
@ilmiyoon we tested it with the integration team on Thursday after class. I forgot to close the issue
