### ISSUE TITLE
Getting blue screen when porting to android

### ISSUE THREAD

**Issue by solid0snake** [worldofbalance/client#83]
Has anyone encountered this?
![screenshot_20160504-122110](https://cloud.githubusercontent.com/assets/1965568/15026401/1da0640a-11f3-11e6-8356-6a40cc8df7fb.png)

Just a blue screen when starting app in android.

**Comment by rujoota** [comment]
@rupalkhilari @dule-hwp did u guys face this issue?

**Comment by dule-hwp** [comment]
Yes. quick fix would be to comment out the the "SpeciesTable.Initialize ();" line in Game.cs.

The code is actually breaking at SpeciesTable.cs on line 14 when it tries to get dataPath. I found somewhere that in order to work on mobile devices this should be Application.persistentDataPath instead of Application.dataPath, but when i tried it, it did not work for me. Since I am not using local database for COS, i just commented this out. I guess this is used to have changes locally so that you can handle connection losing. 

So, if you actually need this piece of code to run, you would have to debug it more than i did. But if you wanna be able to simply run the game on Android, go with commenting that line out for now.
